# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/terminux/Documents/Projects/Electro/Resources/mainui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 521)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.selecteddevicecombobox = QtWidgets.QComboBox(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selecteddevicecombobox.sizePolicy().hasHeightForWidth())
        self.selecteddevicecombobox.setSizePolicy(sizePolicy)
        self.selecteddevicecombobox.setMinimumSize(QtCore.QSize(180, 0))
        self.selecteddevicecombobox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.selecteddevicecombobox.setObjectName("selecteddevicecombobox")
        self.horizontalLayout.addWidget(self.selecteddevicecombobox)
        self.label_2 = QtWidgets.QLabel(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.speedspinbox = QtWidgets.QSpinBox(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedspinbox.sizePolicy().hasHeightForWidth())
        self.speedspinbox.setSizePolicy(sizePolicy)
        self.speedspinbox.setMinimum(1200)
        self.speedspinbox.setMaximum(10000000)
        self.speedspinbox.setObjectName("speedspinbox")
        self.horizontalLayout.addWidget(self.speedspinbox)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.liveplottingtab = QtWidgets.QWidget()
        self.liveplottingtab.setObjectName("liveplottingtab")
        self.gridLayout = QtWidgets.QGridLayout(self.liveplottingtab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.liveplottingtab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.liveplottingcheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.liveplottingcheckbox.setEnabled(False)
        self.liveplottingcheckbox.setChecked(True)
        self.liveplottingcheckbox.setObjectName("liveplottingcheckbox")
        self.gridLayout_7.addWidget(self.liveplottingcheckbox, 0, 0, 1, 1)
        self.loggingcheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.loggingcheckbox.setObjectName("loggingcheckbox")
        self.gridLayout_7.addWidget(self.loggingcheckbox, 0, 1, 1, 1)
        self.filecheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.filecheckbox.setObjectName("filecheckbox")
        self.gridLayout_7.addWidget(self.filecheckbox, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.filepathlineedit = QtWidgets.QLineEdit(self.frame_2)
        self.filepathlineedit.setMinimumSize(QtCore.QSize(300, 0))
        self.filepathlineedit.setObjectName("filepathlineedit")
        self.gridLayout_8.addWidget(self.filepathlineedit, 0, 1, 1, 1)
        self.filepathtoolbutton = QtWidgets.QToolButton(self.frame_2)
        self.filepathtoolbutton.setObjectName("filepathtoolbutton")
        self.gridLayout_8.addWidget(self.filepathtoolbutton, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.customnamecheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.customnamecheckbox.setObjectName("customnamecheckbox")
        self.gridLayout_9.addWidget(self.customnamecheckbox, 0, 0, 1, 1)
        self.filename = QtWidgets.QLineEdit(self.frame_2)
        self.filename.setObjectName("filename")
        self.gridLayout_9.addWidget(self.filename, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_10)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.liveplottingtab, "")
        self.samplingtab = QtWidgets.QWidget()
        self.samplingtab.setObjectName("samplingtab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.samplingtab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.samplingtab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.fromspinbox = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromspinbox.sizePolicy().hasHeightForWidth())
        self.fromspinbox.setSizePolicy(sizePolicy)
        self.fromspinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.fromspinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fromspinbox.setMaximum(0)
        self.fromspinbox.setObjectName("fromspinbox")
        self.gridLayout_4.addWidget(self.fromspinbox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.tospinbox = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tospinbox.sizePolicy().hasHeightForWidth())
        self.tospinbox.setSizePolicy(sizePolicy)
        self.tospinbox.setMinimumSize(QtCore.QSize(100, 0))
        self.tospinbox.setMinimum(10)
        self.tospinbox.setMaximum(5000)
        self.tospinbox.setObjectName("tospinbox")
        self.gridLayout_3.addWidget(self.tospinbox, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.filepathlineedit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.filepathlineedit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.filepathlineedit_2.setObjectName("filepathlineedit_2")
        self.horizontalLayout_5.addWidget(self.filepathlineedit_2)
        self.filepathtoolbutton_2 = QtWidgets.QToolButton(self.frame_3)
        self.filepathtoolbutton_2.setObjectName("filepathtoolbutton_2")
        self.horizontalLayout_5.addWidget(self.filepathtoolbutton_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.customnamecheckbox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.customnamecheckbox_2.setObjectName("customnamecheckbox_2")
        self.gridLayout_5.addWidget(self.customnamecheckbox_2, 2, 0, 1, 1)
        self.filename2 = QtWidgets.QLineEdit(self.frame_3)
        self.filename2.setObjectName("filename2")
        self.gridLayout_5.addWidget(self.filename2, 2, 1, 1, 1)
        self.autoopenfilecheckbox = QtWidgets.QCheckBox(self.frame_3)
        self.autoopenfilecheckbox.setObjectName("autoopenfilecheckbox")
        self.gridLayout_5.addWidget(self.autoopenfilecheckbox, 3, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_5)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.samplingtab, "")
        self.handlerstab = QtWidgets.QWidget()
        self.handlerstab.setEnabled(True)
        self.handlerstab.setObjectName("handlerstab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.handlerstab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.handlerstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.handleractiontype = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.handleractiontype.sizePolicy().hasHeightForWidth())
        self.handleractiontype.setSizePolicy(sizePolicy)
        self.handleractiontype.setObjectName("handleractiontype")
        self.horizontalLayout_3.addWidget(self.handleractiontype)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.operatorcombo = QtWidgets.QComboBox(self.frame)
        self.operatorcombo.setObjectName("operatorcombo")
        self.horizontalLayout_3.addWidget(self.operatorcombo)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.temperaturespinbox = QtWidgets.QSpinBox(self.frame)
        self.temperaturespinbox.setObjectName("temperaturespinbox")
        self.horizontalLayout_3.addWidget(self.temperaturespinbox)
        self.stopmonitorbutton = QtWidgets.QPushButton(self.frame)
        self.stopmonitorbutton.setObjectName("stopmonitorbutton")
        self.horizontalLayout_3.addWidget(self.stopmonitorbutton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shellaction = QtWidgets.QLineEdit(self.frame_4)
        self.shellaction.setObjectName("shellaction")
        self.verticalLayout_2.addWidget(self.shellaction)
        self.electroactions = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electroactions.sizePolicy().hasHeightForWidth())
        self.electroactions.setSizePolicy(sizePolicy)
        self.electroactions.setObjectName("electroactions")
        self.verticalLayout_2.addWidget(self.electroactions)
        self.printedmessage = QtWidgets.QLineEdit(self.frame_4)
        self.printedmessage.setObjectName("printedmessage")
        self.verticalLayout_2.addWidget(self.printedmessage)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.monitoringlabel = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(45)
        self.monitoringlabel.setFont(font)
        self.monitoringlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.monitoringlabel.setTextFormat(QtCore.Qt.RichText)
        self.monitoringlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monitoringlabel.setObjectName("monitoringlabel")
        self.verticalLayout_4.addWidget(self.monitoringlabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.handlerstab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setEnabled(True)
        self.menuSettings.setObjectName("menuSettings")
        self.menuPlotting = QtWidgets.QMenu(self.menubar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionOpen_Plot_File = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open/Icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Plot_File.setIcon(icon)
        self.actionOpen_Plot_File.setObjectName("actionOpen_Plot_File")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/close/Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionopen_settings = QtWidgets.QAction(MainWindow)
        self.actionopen_settings.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/settings/Icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen_settings.setIcon(icon2)
        self.actionopen_settings.setVisible(False)
        self.actionopen_settings.setObjectName("actionopen_settings")
        self.actionStart_Plotting = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/start/Icons/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Plotting.setIcon(icon3)
        self.actionStart_Plotting.setVisible(True)
        self.actionStart_Plotting.setObjectName("actionStart_Plotting")
        self.actionPlottings_UI = QtWidgets.QAction(MainWindow)
        self.actionPlottings_UI.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plot/Icons/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlottings_UI.setIcon(icon4)
        self.actionPlottings_UI.setVisible(False)
        self.actionPlottings_UI.setObjectName("actionPlottings_UI")
        self.actionRefresh_Devices = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/refresh/Icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh_Devices.setIcon(icon5)
        self.actionRefresh_Devices.setObjectName("actionRefresh_Devices")
        self.actionClear_Device_List = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/clear/Icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_Device_List.setIcon(icon6)
        self.actionClear_Device_List.setObjectName("actionClear_Device_List")
        self.actionRestore_All = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/restoreall/Icons/restoreall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestore_All.setIcon(icon7)
        self.actionRestore_All.setObjectName("actionRestore_All")
        self.actionRestore_Tab = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/restoretab/Icons/restoretab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestore_Tab.setIcon(icon8)
        self.actionRestore_Tab.setObjectName("actionRestore_Tab")
        self.menuFile.addAction(self.actionOpen_Plot_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuSettings.addAction(self.actionopen_settings)
        self.menuSettings.addAction(self.actionRefresh_Devices)
        self.menuSettings.addAction(self.actionClear_Device_List)
        self.menuSettings.addAction(self.actionRestore_All)
        self.menuSettings.addAction(self.actionRestore_Tab)
        self.menuPlotting.addAction(self.actionStart_Plotting)
        self.menuPlotting.addAction(self.actionPlottings_UI)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPlotting.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.toolBar.addAction(self.actionOpen_Plot_File)
        self.toolBar.addAction(self.actionStart_Plotting)
        self.toolBar.addAction(self.actionRefresh_Devices)
        self.toolBar.addAction(self.actionClear_Device_List)
        self.toolBar.addAction(self.actionPlottings_UI)
        self.toolBar.addAction(self.actionRestore_All)
        self.toolBar.addAction(self.actionRestore_Tab)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electro"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "USB and Plotting Settings"))
        self.label.setText(_translate("MainWindow", "USB Device"))
        self.label_2.setText(_translate("MainWindow", "Speed"))
        self.liveplottingcheckbox.setText(_translate("MainWindow", "Live Plotting"))
        self.loggingcheckbox.setText(_translate("MainWindow", "Logging"))
        self.filecheckbox.setText(_translate("MainWindow", "File Recording"))
        self.label_3.setText(_translate("MainWindow", "Filepath Recording"))
        self.filepathtoolbutton.setText(_translate("MainWindow", "..."))
        self.customnamecheckbox.setText(_translate("MainWindow", "Custom name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.liveplottingtab), _translate("MainWindow", "Live Plotting"))
        self.label_5.setText(_translate("MainWindow", "From"))
        self.label_6.setText(_translate("MainWindow", "To"))
        self.label_4.setText(_translate("MainWindow", "Filepath Recording"))
        self.filepathtoolbutton_2.setText(_translate("MainWindow", "..."))
        self.customnamecheckbox_2.setText(_translate("MainWindow", "Custom Name"))
        self.autoopenfilecheckbox.setText(_translate("MainWindow", "Auto Open"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.samplingtab), _translate("MainWindow", "Sampling"))
        self.label_7.setText(_translate("MainWindow", "Action Type"))
        self.label_8.setText(_translate("MainWindow", "Operator"))
        self.label_9.setText(_translate("MainWindow", "Temperature"))
        self.stopmonitorbutton.setText(_translate("MainWindow", "Stop"))
        self.monitoringlabel.setText(_translate("MainWindow", "Monitoring"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.handlerstab), _translate("MainWindow", "Handlers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Electro"))
        self.menuPlotting.setTitle(_translate("MainWindow", "Plotting"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_Plot_File.setText(_translate("MainWindow", "Open Plot File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionopen_settings.setText(_translate("MainWindow", "Settings"))
        self.actionStart_Plotting.setText(_translate("MainWindow", "Start Plotting"))
        self.actionPlottings_UI.setText(_translate("MainWindow", "Plottings UI (exp)"))
        self.actionRefresh_Devices.setText(_translate("MainWindow", "Refresh Devices"))
        self.actionClear_Device_List.setText(_translate("MainWindow", "Clear Device List"))
        self.actionRestore_All.setText(_translate("MainWindow", "Restore All"))
        self.actionRestore_All.setToolTip(_translate("MainWindow", "Restore all tab settings to default"))
        self.actionRestore_Tab.setText(_translate("MainWindow", "Restore Tab"))
        self.actionRestore_Tab.setToolTip(_translate("MainWindow", "Restore the selected tab to default"))

import ElectroRes_rc
